/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ec.gob.firmadigital.firmador;

import ec.gob.firmadigital.utils.PropertiesUtils;
import io.rubrica.utils.FileUtils;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jdc
 */
public class JPanelAcercaDe extends javax.swing.JPanel {

    private static final Logger logger = Logger.getLogger(JPanelAcercaDe.class.getName());
    private static final String URL = "https://www.telecomunicaciones.gob.ec";
    private String log = System.getProperty("user.home") + "/firmadigital.log";

    /**
     * Creates new form jplAcercaDe
     */
    public JPanelAcercaDe() {
        initComponents();
        jlbEtiqueta1.setText("<html><div style='text-align: center;'>FirmaEC - Firma Electrónica Ecuador</div></html>");
        jlbEtiqueta2.setText("<html><div style='text-align: center;'>Sistema desarrollado por:<br/>Subsecretaría de Gobierno Electrónico<br/>Ministerio de Telecomunicaciones y Sociedad de la Información</div></html>");
        jlbUrl.setText("<html><div style='text-align: center;'><u>" + URL + "</u></div></html>");
        jlbLog.setText("<html><div style='text-align: center;'>" + "Registro del sistema: " + "<u>" + log + "</u></div></html>");

        jlbUrl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI(URL));
                } catch (URISyntaxException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jlbLog.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    FileUtils.abrirDocumento(log);
                } catch (IOException | java.lang.IllegalArgumentException ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, "No se generó ningún registro", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        Properties config = PropertiesUtils.getConfig();
        this.jlbVersion.setText("Versión: " + config.getProperty("version") + " - " + config.getProperty("fecha"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbEtiqueta1 = new javax.swing.JLabel();
        jlbEtiqueta2 = new javax.swing.JLabel();
        jlbUrl = new javax.swing.JLabel();
        jlbVersion = new javax.swing.JLabel();
        jlbLog = new javax.swing.JLabel();

        jlbEtiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbEtiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jlbUrl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbEtiqueta2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbEtiqueta1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbVersion, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbLog, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jlbUrl, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlbEtiqueta1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbEtiqueta2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLog, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbEtiqueta1;
    private javax.swing.JLabel jlbEtiqueta2;
    private javax.swing.JLabel jlbLog;
    private javax.swing.JLabel jlbUrl;
    private javax.swing.JLabel jlbVersion;
    // End of variables declaration//GEN-END:variables
}
